# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/app/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YouTubeVideoDownloader(object):
    def setupUi(self, YouTubeVideoDownloader):
        YouTubeVideoDownloader.setObjectName("YouTubeVideoDownloader")
        YouTubeVideoDownloader.resize(345, 402)
        self.centralwidget = QtWidgets.QWidget(YouTubeVideoDownloader)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        YouTubeVideoDownloader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(YouTubeVideoDownloader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 22))
        self.menubar.setObjectName("menubar")
        YouTubeVideoDownloader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(YouTubeVideoDownloader)
        self.statusbar.setObjectName("statusbar")
        YouTubeVideoDownloader.setStatusBar(self.statusbar)

        self.retranslateUi(YouTubeVideoDownloader)
        QtCore.QMetaObject.connectSlotsByName(YouTubeVideoDownloader)

    def retranslateUi(self, YouTubeVideoDownloader):
        _translate = QtCore.QCoreApplication.translate
        YouTubeVideoDownloader.setWindowTitle(_translate("YouTubeVideoDownloader", "YouTube Video Downloader"))
        self.label.setText(_translate("YouTubeVideoDownloader", "Paste your link here:"))
        self.pushButton.setText(_translate("YouTubeVideoDownloader", "Download"))
        self.pushButton_2.setText(_translate("YouTubeVideoDownloader", "Cancel"))

        import qtawesome as qta
        icon = qta.icon("fa5s.download")
        self.pushButton.setIcon(icon)

        icon_2 = qta.icon("ri.stop-circle-line")
        self.pushButton_2.setIcon(icon_2)

        icon_3 = qta.icon("mdi.folder-download")
        self.pushButton_3.setIcon(icon_3)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YouTubeVideoDownloader = QtWidgets.QMainWindow()
    ui = Ui_YouTubeVideoDownloader()
    ui.setupUi(YouTubeVideoDownloader)
    YouTubeVideoDownloader.show()
    sys.exit(app.exec_())
